"""empty message

Revision ID: 41119fab3584
Revises: b2eea00c325c
Create Date: 2022-10-18 04:24:53.726359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41119fab3584'
down_revision = 'b2eea00c325c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_name', sa.VARCHAR(length=25), nullable=False))
    op.add_column('users', sa.Column('last_name', sa.VARCHAR(length=25), nullable=False))
    op.add_column('users', sa.Column('previewImageUrl', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'previewImageUrl')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###
